spring:
  application:
    name: 13-SpringBoot-Microservices-Greet-API
  boot:
    admin:
      client:
        url: http://localhost:1111/

server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: '*'